### ISSUE TITLE
Refactor build environment

### ISSUE THREAD

**Issue by thomaskrause** [hexatomic/hexatomic#1]

**Comment by thomaskrause** [comment]
I think this is more important.

**Comment by sdruskat** [comment]
I think we should probably do a new GitHub project for these things (i.e., releng, architecture, refactoring, etc.), and keep https://github.com/hexatomic/hexatomic/projects/1 for features.

**Comment by sdruskat** [comment]
@thomaskrause I guess this refers to creating a buildable/CI-able version in the first place? If so, #13 will do just this.
