### ISSUE TITLE
Simple corpus creation

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#10]
- [ ] ~Paste text (1 corpus, 1 docu, 1 text)~ (not part of GraphAnno)
- [x] "Open file" (dto.)
- [x] "Open directory"

**Comment by sdruskat** [comment]
Latter 2 options via Pepper TextImporter

**Comment by thomaskrause** [comment]
We support both creating new corpora from existing text files but also the "GraphAnno way" to create a new document and add tokens with the `t` command
