### ISSUE TITLE
Integration test for TestCorpusStructure fails locally

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#127]
**Describe the bug**

When running `mvn clean install` on https://github.com/hexatomic/hexatomic/pull/117, the build fails.

**To reproduce the bug**
1. `git checkout feature/zest-graph-view`
2. `git pull`
3. `mvn clean install`
4. Build fails with stack trace:

```
Running org.corpus_tools.hexatomic.it.tests.TestGraphEditor
log4j:WARN No appenders could be found for logger (org.eclipse.swtbot.swt.finder.matchers.AbstractMatcher).
log4j:WARN Please initialize the log4j system properly.
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(org.corpus_tools.hexatomic:26489): Gtk-CRITICAL **: 21:07:47.690: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(org.corpus_tools.hexatomic:26489): Gtk-WARNING **: 21:07:47.690: gtk_widget_size_allocate(): attempt to allocate widget with width 12 and height -13

(org.corpus_tools.hexatomic:26489): Gtk-CRITICAL **: 21:07:47.690: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.532 s - in org.corpus_tools.hexatomic.it.tests.TestGraphEditor
testShowSaltExample  Time elapsed: 0.422 s
Running org.corpus_tools.hexatomic.it.tests.TestCorpusStructure
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 10.294 s <<< FAILURE! - in org.corpus_tools.hexatomic.it.tests.TestCorpusStructure
testRenameDocument  Time elapsed: 5.273 s  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Timed out waiting for tree item corpus_graph_1
	at org.corpus_tools.hexatomic.it.tests.TestCorpusStructure.testRenameDocument(TestCorpusStructure.java:34)
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find node with text corpus_graph_1
	at org.corpus_tools.hexatomic.it.tests.TestCorpusStructure.testRenameDocument(TestCorpusStructure.java:34)

testFilter  Time elapsed: 5.018 s  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget matching: (of type 'Tree')
	at org.corpus_tools.hexatomic.it.tests.TestCorpusStructure.testFilter(TestCorpusStructure.java:72)
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find widget matching: (of type 'Tree')
	at org.corpus_tools.hexatomic.it.tests.TestCorpusStructure.testFilter(TestCorpusStructure.java:72)


Results:

Errors: 
  TestCorpusStructure.testFilter:72 » WidgetNotFound Could not find widget match...
  TestCorpusStructure.testRenameDocument:34 » WidgetNotFound Timed out waiting f...

Tests run: 3, Failures: 0, Errors: 2, Skipped: 0

```

**Expected behavior**

Integration tests pass locally.

**Screenshots**

![image](https://user-images.githubusercontent.com/3007126/73782698-d1455280-4792-11ea-9573-05063af3ff1c.png)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 18.04
 - Hexatomic Version: https://github.com/hexatomic/hexatomic/pull/117
 - Java Version: OpenJDK 8

**Comment by sdruskat** [comment]
Weirdly, the corpus graph is called "corpusGraph1" where it shold be called "corpus_graph_1".

**Comment by sdruskat** [comment]
When running the product and clicking "Add" manually, the corpus graph is indeed called "corpus_graph_1".

**Comment by sdruskat** [comment]
Ah, the problem is that TestGraphEditor is run beforehand, and the workspace isn't cleared in between tests.

**Comment by sdruskat** [comment]
@costezki Thanks for your heads up, do you run this on the latest `develop`?

**Comment by costezki** [comment]
yes, the commit humber is 308b80f449c2955ff5e9083777a6135e9e50f39e (from 29th of May)

**Comment by sdruskat** [comment]
Thanks, we'll investigate.

Can you give us details about the Eclipse you're running, and the OS + Java details please?

**Comment by sdruskat** [comment]
Please also provide the stack trace. Do the tests run from within Eclipse?

**Comment by costezki** [comment]
In bash I run 
```
mvn clean install
```

JVM: 
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

Maven:
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_252, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-33-generic", arch: "amd64", family: "unix"

[stack-trace.log](https://github.com/hexatomic/hexatomic/files/4728389/stack-trace.log)

Note: The process comes to a successful termination if I skip tests.

**Comment by sdruskat** [comment]
Thanks, seems as if the SWTBot tests miss some dependencies/locales. We'll look into it.

**Comment by sdruskat** [comment]
Right, I can reproduce the issue on Ubuntu with the following `locale` settings:

```
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

Caused by:

```log
java.lang.ExceptionInInitializerError
	at org.corpus_tools.hexatomic.it.tests.TestCorpusStructure.createExampleStructure(TestCorpusStructure.java:90)
	at org.corpus_tools.hexatomic.it.tests.TestCorpusStructure.testRenameDocument(TestCorpusStructure.java:103)
Caused by: java.lang.IllegalArgumentException: EN_GB.keyboard not found, see http://wiki.eclipse.org/SWTBot/Keyboard_Layouts for more information.
	at org.corpus_tools.hexatomic.it.tests.TestCorpusStructure.createExampleStructure(TestCorpusStructure.java:90)
	at org.corpus_tools.hexatomic.it.tests.TestCorpusStructure.testRenameDocument(TestCorpusStructure.java:103)
```

**Comment by sdruskat** [comment]
@costezki Please checkout https://github.com/hexatomic/hexatomic/tree/feature/test-keyboard-layout and let me know if that fixes the issue for you. (I think you need to have the `en_US.UTF-8` locale at least generated, so that it is available via `locale -a`).

**Comment by costezki** [comment]
I could not find the branch https://github.com/hexatomic/hexatomic/tree/feature/test-keyboard-layout and I assumed that it was merged into /develop. 

Just ran another mvn clean install, getting this time as an outcome the following exception:

> [INFO] Command line:
> 	[/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -Dosgi.clean=true, -jar, /home/lps/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.5.700.v20200207-2156/org.eclipse.equinox.launcher-1.5.700.v20200207-2156.jar, -data, /home/lps/work/workspace-charm/hexatomic/tests/org.corpus_tools.hexatomic.it.tests/target/work/data, -install, /home/lps/work/workspace-charm/hexatomic/tests/org.corpus_tools.hexatomic.it.tests/target/work, -configuration, /home/lps/work/workspace-charm/hexatomic/tests/org.corpus_tools.hexatomic.it.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /home/lps/work/workspace-charm/hexatomic/tests/org.corpus_tools.hexatomic.it.tests/target/surefire.properties, -testApplication, org.eclipse.e4.ui.workbench.swt.E4Application, -product, org.corpus_tools.hexatomic.core.product, -nouithread]
> Launching application org.eclipse.e4.ui.workbench.swt.E4Application...
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> Running org.corpus_tools.hexatomic.it.tests.TestCorpusStructure
> log4j:WARN No appenders could be found for logger (org.eclipse.swtbot.swt.finder.matchers.AbstractMatcher).
> log4j:WARN Please initialize the log4j system properly.
> Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.546 s - in org.corpus_tools.hexatomic.it.tests.TestCorpusStructure
> testRenameDocument  Time elapsed: 0.248 s
> testFilter  Time elapsed: 0.18 s
> Running org.corpus_tools.hexatomic.it.tests.TestGraphEditor
> Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 11.23 s <<< FAILURE! - in org.corpus_tools.hexatomic.it.tests.TestGraphEditor
> testShowSaltExample  Time elapsed: 0.583 s
> testTokenizeSelectedTextualDS  Time elapsed: 5.607 s  <<< ERROR!
> org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Showing the graph editor part took too long
> 	at org.corpus_tools.hexatomic.it.tests.TestGraphEditor.openDefaultExample(TestGraphEditor.java:112)
> 	at org.corpus_tools.hexatomic.it.tests.TestGraphEditor.testTokenizeSelectedTextualDS(TestGraphEditor.java:221)
> 
> testAddPointingRelation  Time elapsed: 5.038 s  <<< ERROR!
> org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget matching: (of type 'Tree')
> 	at org.corpus_tools.hexatomic.it.tests.TestGraphEditor.openDefaultExample(TestGraphEditor.java:105)
> 	at org.corpus_tools.hexatomic.it.tests.TestGraphEditor.testAddPointingRelation(TestGraphEditor.java:189)
> Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find widget matching: (of type 'Tree')
> 	at org.corpus_tools.hexatomic.it.tests.TestGraphEditor.openDefaultExample(TestGraphEditor.java:105)
> 	at org.corpus_tools.hexatomic.it.tests.TestGraphEditor.testAddPointingRelation(TestGraphEditor.java:189)
> 
> Running org.corpus_tools.hexatomic.it.tests.TestGridEditor
> Tests run: 18, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 33.518 s <<< FAILURE! - in org.corpus_tools.hexatomic.it.tests.TestGridEditor
> testShowSaltExample  Time elapsed: 5.025 s  <<< ERROR!
> org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget matching: (of type 'Tree')
> 	at org.corpus_tools.hexatomic.it.tests.TestGridEditor.openDefaultExample(TestGridEditor.java:164)
> 	at org.corpus_tools.hexatomic.it.tests.TestGridEditor.testShowSaltExample(TestGridEditor.java:240)
> Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find widget matching: (of type 'Tree')
> 	at org.corpus_tools.hexatomic.it.tests.TestGridEditor.openDefaultExample(TestGridEditor.java:164)
> 	at org.corpus_tools.hexatomic.it.tests.TestGridEditor.testShowSaltExample(TestGridEditor.java:240)
> 
> testEditCellTyping  Time elapsed: 5.027 s  <<< ERROR!
> org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget matching: (of type 'Tree')
> 	at org.corpus_tools.hexatomic.it.tests.TestGridEditor.openDefaultExample(TestGridEditor.java:164)
> 	at org.corpus_tools.hexatomic.it.tests.TestGridEditor.testEditCellTyping(TestGridEditor.java:437)
> Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find widget matching: (of type 'Tree')
> 	at org.corpus_tools.hexatomic.it.tests.TestGridEditor.openDefaultExample(TestGridEditor.java:164)
> 	at org.corpus_tools.hexatomic.it.tests.TestGridEditor.testEditCellTyping(TestGridEditor.java:437)
> 
> testDsSelection  Time elapsed: 1.197 s
> testPopupMenuInvisibleOnNoSelection  Time elapsed: 5.646 s
> testDropdownWithTwoTexts  Time elapsed: 0.65 s
> testCreateAnnotationOnEmptySpanCell  Time elapsed: 1.363 s
> testEditCellSpaceActivatedTyping  Time elapsed: 1.325 s
> testShowOverlapSaltExample  Time elapsed: 0.587 s
> testHideShowColumns  Time elapsed: 0.696 s
> testDropdownWithSingleText  Time elapsed: 0.596 s
> testPopupMenuInvisibleOnSelectedTokenText  Time elapsed: 5.61 s
> testRowPopupMenu  Time elapsed: 0.609 s
> testEditCellOnDoubleClick  Time elapsed: 1.321 s
> testEmptyCellStyleApplied  Time elapsed: 0.576 s
> testRemoveSingleAnnotationByDelKey  Time elapsed: 0.683 s
> testCreateAnnotationOnEmptyTokenCell  Time elapsed: 1.328 s
> testRemoveSingleAnnotationByPopupMenu  Time elapsed: 0.637 s
> testColumnPopupMenu  Time elapsed: 0.609 s
> Running org.corpus_tools.hexatomic.it.tests.TestProjectManager
> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.949 s - in org.corpus_tools.hexatomic.it.tests.TestProjectManager
> testOpenAndSave  Time elapsed: 0.949 s
> 
> Results:
> 
> Errors: 
>   TestGraphEditor.testAddPointingRelation:189->openDefaultExample:105 » WidgetNotFound
>   TestGraphEditor.testTokenizeSelectedTextualDS:221->openDefaultExample:112 » Timeout
>   TestGridEditor.testEditCellTyping:437->openDefaultExample:164 » WidgetNotFound
>   TestGridEditor.testShowSaltExample:240->openDefaultExample:164 » WidgetNotFound
> 
> Tests run: 24, Failures: 0, Errors: 4, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for org.corpus_tools.hexatomic.root 0.4.0-SNAPSHOT:
> [INFO] 
> [INFO] org.corpus_tools.hexatomic.root .................... SUCCESS [  1.696 s]
> [INFO] org.corpus_tools.hexatomic.bundles ................. SUCCESS [  1.769 s]
> [INFO] org.corpus_tools.hexatomic.core .................... SUCCESS [  4.016 s]
> [INFO] org.corpus_tools.hexatomic.corpusstructureeditor ... SUCCESS [  3.103 s]
> [INFO] org.corpus_tools.hexatomic.textviewer .............. SUCCESS [  2.589 s]
> [INFO] org.corpus_tools.hexatomic.graph ................... SUCCESS [  5.607 s]
> [INFO] org.corpus_tools.hexatomic.grid .................... SUCCESS [  3.047 s]
> [INFO] org.corpus_tools.hexatomic.features ................ SUCCESS [  0.059 s]
> [INFO] org.corpus_tools.hexatomic ......................... SUCCESS [  0.474 s]
> [INFO] org.corpus_tools.hexatomic.releng .................. SUCCESS [  0.074 s]
> [INFO] org.corpus_tools.hexatomic.update .................. SUCCESS [  1.094 s]
> [INFO] org.corpus_tools.hexatomic.product ................. SUCCESS [ 13.276 s]
> [INFO] org.corpus_tools.hexatomic.target .................. SUCCESS [  0.121 s]
> [INFO] org.corpus_tools.hexatomic.tests ................... SUCCESS [  0.081 s]
> [INFO] org.corpus_tools.hexatomic.core.tests .............. SUCCESS [  3.472 s]
> [INFO] org.corpus_tools.hexatomic.graph.tests ............. SUCCESS [  2.356 s]
> [INFO] org.corpus_tools.hexatomic.grid.tests .............. SUCCESS [  3.876 s]
> [INFO] org.corpus_tools.hexatomic.it.tests ................ FAILURE [ 49.896 s]
> [INFO] Aggregate Test Report .............................. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  01:52 min
> [INFO] Finished at: 2020-06-05T11:28:11+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:1.6.0:test (default-test) on project org.corpus_tools.hexatomic.it.tests: There are test failures.
> [ERROR] 
> [ERROR] Please refer to /home/lps/work/workspace-charm/hexatomic/tests/org.corpus_tools.hexatomic.it.tests/target/surefire-reports for the individual test results.
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :org.corpus_tools.hexatomic.it.tests
> 
>

**Comment by sdruskat** [comment]
Thanks @costezki. Could it be that per chance you have done other work while letting the build run in the background? Clicking anything or typing anything while the UI tests run will trip the tests, we need to document this. If this is the case, could you please try and run again without doing any other work at the same time?

Thanks!

**Comment by costezki** [comment]
Yes, indeed the tests pass when I do no other actions on the computer. Thank you.

**Comment by sdruskat** [comment]
Perfect! Thanks for the feedback.
