### ISSUE TITLE
Fix unexpected selection behaviour in filter list of graph viewer

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#130]
**Describe the bug**

When selecting segments in the filter list, and then including and excluding spans via the "Include spans" checkbox, the resulting selections are erratic.

![filter](https://user-images.githubusercontent.com/3007126/73929065-774ca600-48d4-11ea-987b-90c453cd4f97.gif)

**To reproduce the bug**
1. Open a project
2. Open a document with more than one text in the graph viewer
3. Select a segment X
4. Check "Include Spans"
5. Result: First segment in the list is selected, instead of all relevant segments under the selected X
6. Select all relevant segments under X and X
7. Uncheck "Include Spans"
8. Segment X and n following segments are selected, instead of just segment X

**Expected behavior**

See above, a) segments under the selected segment are selected when spans are included, and b) on the root segments of all segments previously selected are selected when spans are excluded.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: [e.g. Ubuntu 18.04]
 - Hexatomic Version: [e.g. 1.0.3]
 - Java Version: [e.g. OpenJDK 8, Oracle JDK 11]
 

**Additional context**

**Comment by sdruskat** [comment]
The place to fix this will probably be https://github.com/hexatomic/hexatomic/blob/a8d368cf17427935455903d62c61406ea2e7f2ee/bundles/org.corpus_tools.hexatomic.graph/src/main/java/org/corpus_tools/hexatomic/graph/GraphEditor.java#L362-L412

**Comment by thomaskrause** [comment]
This behaviour was fixed in PR #124. The selection is now retained when the filters are changed and always includes the same text as selected before (even if there are new segments). Please re-open if you still experience this bug.
