### ISSUE TITLE
Graph editor: inserting tokens with 'ta' or 'tb' throws StringIndexOutOfRangeException when >1 text in domain, tokens are deleted/shortened

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#140]
**Describe the bug**

When segements are selected that overlap >1 `STextualDS`, and a token is inserted with `ta` or `tb`, an SIOORE is thrown.

*However*, the token is still added to the right `STextualDS` (in contrast to #139).

It also seems that this affects the tokens in other segments, which are deleted and/or shortened.

**To reproduce the bug**
1. Open a document containing more than 1 DS in the graph editor
2. Select segments that overlap more than on DS (between each other, not individually)
3. Insert a token with `ta` or `tb`
4. SIOORE is thrown
5. Token is still inserted into the correct text.
6. Tokens in other segments are deleted/shortened.

**Expected behavior**

I'd expect no exception, instead correct insertion of the token, correct visual feedback (token appearing in the graph), and no side effects on other segments.

**Screenshots**

Wait till you see this in action 😱:

![addtoken](https://user-images.githubusercontent.com/3007126/74038662-d8ea3e80-49c0-11ea-9a92-6dda1e53e51a.gif)

**Desktop (please complete the following information):**
 - Operating System: [e.g. Ubuntu 18.04]
 - Hexatomic Version: [e.g. 1.0.3]
 - Java Version: [e.g. OpenJDK 8, Oracle JDK 11]
 

**Additional context**

**Comment by thomaskrause** [comment]
From the experience of fixing #139 and how `ta` and `tb` are implemented, this seems to be a bug in Salt in the [insertTokensAt](https://github.com/korpling/salt/blob/523eae74010b568c15f3317784e39b329f6210a1/salt-api/src/main/java/org/corpus_tools/salt/common/impl/SDocumentGraphImpl.java#L844) function. It iterates over all textual relations to update the offset (so this is not a problem when inserting a token at the end) and adds the offset. But it does this even with the textual relations pointing to another `STextualDS`.

**Comment by sdruskat** [comment]
> From the experience of fixing #139 and how `ta` and `tb` are implemented, this seems to be a bug in Salt in the [insertTokensAt](https://github.com/korpling/salt/blob/523eae74010b568c15f3317784e39b329f6210a1/salt-api/src/main/java/org/corpus_tools/salt/common/impl/SDocumentGraphImpl.java#L844) function. It iterates over all textual relations to update the offset (so this is not a problem when inserting a token at the end) and adds the offset. But it does this even with the textual relations pointing to another `STextualDS`.

Well, luckily the project is called *A minimal infrastructure for the sustainable provision of extensible multi-layer annotation software for linguistic corpora, and fixing Salt* ;)

**Comment by thomaskrause** [comment]
> > From the experience of fixing #139 and how `ta` and `tb` are implemented, this seems to be a bug in Salt in the [insertTokensAt](https://github.com/korpling/salt/blob/523eae74010b568c15f3317784e39b329f6210a1/salt-api/src/main/java/org/corpus_tools/salt/common/impl/SDocumentGraphImpl.java#L844) function. It iterates over all textual relations to update the offset (so this is not a problem when inserting a token at the end) and adds the offset. But it does this even with the textual relations pointing to another `STextualDS`.
> 
> Well, luckily the project is called _A minimal infrastructure for the sustainable provision of extensible multi-layer annotation software for linguistic corpora, and fixing Salt_ ;)

Well, a sustainable software is only as sustainable as their most unsustainable dependency 😺
