### ISSUE TITLE
Graph editor: Labels in graph not updated after edge annotation

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#143]
**Is your feature request related to a problem? Please describe.**

~I need Hexatomic to let me annotate existing edges in the graph editor.~

**Describe the solution you'd like**

~This should work the same way as annotating nodes.~

~1. If the edge has an identifier (must be displayed, at least in a tooltip if we don't want to clutter the UI), use that, e.g., `a x:y #e1`.~
~2. If it doesn't have an identifier, identify it via the nodes it connects, e.g., `a x:y #n1 > #t1`.~

This all works fine (and indeed in both syntaxes, `a x:y #n1 > #t1` **and** `a #n1 > #t1 x:y`), but the edge labels aren't updated. You can only see them when deselecting and reselecting the segment!

![edge](https://user-images.githubusercontent.com/3007126/74042077-29649a80-49c7-11ea-9733-2e021c81dd26.gif)

**Describe alternatives you've considered**

n/a

**Comment by sdruskat** [comment]
This bug also holds for the creation of new edges with `e`, where the edge is seen instantly, but the annotation only after reselection of the segment.

**Comment by thomaskrause** [comment]
It seems that the labels don't have a container set when the update event is fired. Without a container, the graph view does not know if the update actually belongs to the correct graphs and bails out.

**Comment by thomaskrause** [comment]
Fixed in #150 by updating to a fixed Salt version. This was a bug in the notification system of Salt. For relations,the wrong listener list was used and no event was fired.
