### ISSUE TITLE
Document that ErrorService can only be injected into classes registered in the application context

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#152]
**Describe the bug**

https://hexatomic.github.io/hexatomic/dev/v0.3/development/logging-error-handling.html should describe the prerequisites for injecting and using the error service.

**To reproduce the bug**
1. Create a bundle
2. Inject `ErrorService` into a class that is not, e.g., an `MPart`
3. Use `ErrorService` instance
3. NPE (`ErrorService` is `null`).

**Expected behavior**

I'd like to find out (from the docs) why injecting and using the `ErrorService` throws an NPE, or rather, how it is injected, i.e., that it can only be injected into "context classes", and must be passed on if it should be used in any non-context classes.

It can be discussed, whether these "other" classes should be able to get a hold of the service at all...

**Comment by sdruskat** [comment]
Cf. https://github.com/hexatomic/hexatomic/blob/a95509d58b86c3b6f1c3d6691d1d25a2fb233df4/bundles/org.corpus_tools.hexatomic.edit.grid/src/main/java/org/corpus_tools/hexatomic/edit/grid/data/GraphDataProvider.java#L66-L67

And then https://github.com/hexatomic/hexatomic/blob/a95509d58b86c3b6f1c3d6691d1d25a2fb233df4/bundles/org.corpus_tools.hexatomic.edit.grid/src/main/java/org/corpus_tools/hexatomic/edit/grid/data/GraphDataProvider.java#L160-L161

**Comment by thomaskrause** [comment]
We already link to the general description of how dependency injection works in the "Data model" section (http://web.archive.org/web/20190807184652/https://www.vogella.com/tutorials/EclipseRCP/article.html#dependency-injection-and-eclipse). We might also add the link in this chapter and/or link Eclipse RCP documentation about dependency injection, but we should not try to write our own RCP docs.

**Comment by thomaskrause** [comment]
I changed the label from "bug" to "docs-dev-maint" because I think the former one is not appropriate. The described behaviour is how Eclipse RCP works and there is nothing wrong with it. Also, the documentation is not specific at this point, but it actually does not claim you can use it in classes not handled by the Eclipse RCP dependency injection context.

**Comment by thomaskrause** [comment]
I actually found a solution how to use the injected services in the UI integration tests.
The trick is, that we already have the `IEclipseContext` via the `ContextHelper` class. 
We can then call `ContextInjectionFactory.make(...)` to get an instance of the actual valid service.
```java
import org.eclipse.e4.core.contexts.ContextInjectionFactory;
import org.eclipse.e4.core.contexts.IEclipseContext;

/* ... */

  ProjectManager projectManager;

  @BeforeEach
  void setup() {
    IEclipseContext ctx = ContextHelper.getEclipseContext();

    projectManager = ContextInjectionFactory.make(ProjectManager.class, ctx);
  }
```

I'm using this in the `feature/save-project` branch to call the `ProjectManager`directly and get the  Salt graphs: https://github.com/hexatomic/hexatomic/blob/5a666cbf467df15a49b507b11e74f3689d81271d/tests/org.corpus_tools.hexatomic.it.tests/src/main/java/org/corpus_tools/hexatomic/it/tests/TestProjectManager.java#L103

**Comment by sdruskat** [comment]
Document as choice between passing service to constructor or use DI.
