### ISSUE TITLE
All same-type same-direction relations between same nodes are annotated at the same time

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#155]
**Describe the bug**

Related to #154, this is of course entirely due to the fact that relations cannot currently be identified.

Create the same type of relation between the same nodes twice, then annotate and behold the same annotation being added twice.

**Expected behavior**

Relations are given an id so that they can be identified in annotation and other operations on relations.

**Screenshots**

![image](https://user-images.githubusercontent.com/3007126/75028748-2080c800-54a1-11ea-8e38-bb64e301f136.png)

**Comment by thomaskrause** [comment]
I think a definition of "add annotation to all matching items" is much better than throwing an error or enforcing an ID. E.g. in future versions we could deliberately allow to have patterns of edges and annotate all of them in the same time.

We can add an enhancement to "find a way to identify edge" by e.g. type and/or index but this in my opinion this is not a bug, but actually a feature that is consistent with the other behaviour of the console (e.g. having multiple node arguments which will all get the same annotation).
