### ISSUE TITLE
Deal with timing-related SWTBot test failures

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#159]
Sometimes, test failures happen, which seem to be timing-related, e.g., something like

```
Launching application org.eclipse.e4.ui.workbench.swt.E4Application...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Running org.corpus_tools.hexatomic.it.tests.TestCorpusStructure
log4j:WARN No appenders could be found for logger (org.eclipse.swtbot.swt.finder.matchers.AbstractMatcher).
log4j:WARN Please initialize the log4j system properly.
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.634 s <<< FAILURE! - in org.corpus_tools.hexatomic.it.tests.TestCorpusStructure
testRenameDocument  Time elapsed: 0.366 s
testFilter  Time elapsed: 0.134 s  <<< ERROR!
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.corpus_tools.hexatomic.it.tests.TestCorpusStructure.testFilter(TestCorpusStructure.java:103)
```

This is expanding the tree in the the Project Manager, but it seems that it doesn't do so quickly enough (UI is lagging some ms), and therefore we get this error.

This depends on hardware and current workload of the test machine I guess, but may be off-putting for external users which may wonder why this test fails.

What do we want to do about this?

**Comment by sdruskat** [comment]
Guess this should be solved with `waitUntil(condition)`...

**Comment by thomaskrause** [comment]
I think this specific issue you described was caused by the way we entered the the new names of the documents when renaming them. The text field content was changed with `setText()`and then an enter keystroke was inserted. In #156 I changed this to the `typeText()` method of SWTBot, which seems to be much more reliable in this case. Since `typeText()` has a certain delay, It might not be suited for all kinds of scenarios (typing long texts would take a long time).

**Comment by thomaskrause** [comment]
I added a PR for this specific issue. In general, SWTBot already has some waiting when it tries to select elements. We should try to watch out for `setText()` in new PRs and check that there are no other flaky tests in the current test suite or introduced by new PRs.
