### ISSUE TITLE
Use colors and font styles for annotation entities consistently

### ISSUE THREAD

**Issue by thomaskrause** [hexatomic/hexatomic#173]
**Is your feature request related to a problem? Please describe.**
Currently, every editor has its own colour scheme and uses different colours/font styles for the same entities. E.g. the grid editor uses a dark green for spans and italic font for tokens, but the graph editor uses a bright green for tokens.

**Describe the solution you'd like**
It would be nice, if the basic editors we provide as a Hexatomic project follow a common colour scheme for annotated entities.

**Comment by sdruskat** [comment]
Yep, thought about that while working on the grid editor. We should also make sure that we follow WCAG to keep it accessible. I'd even say we should look into accessible full colour schemes, which we can re-use for the product as such.
