### ISSUE TITLE
Implement all-contributors specs

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#19]
- [x] Install the all-contributors bot
- [x] Add the project team with their contribs
- [x] Include note on how to add to contribs table in templates for issues

(The last two so that contributors can add themselves rather than us having to do all the work.)

To credit all contributors to Hexatomic, we should implement the [all-contributors](https://allcontributors.org/) specs via installing the bot.

**Comment by sdruskat** [comment]
@thomaskrause Any opposition?

**Comment by sdruskat** [comment]
Here is the list of roles/emojis: https://allcontributors.org/docs/en/emoji-key

**Comment by sdruskat** [comment]
@all-contributors please add @sdruskat for maintenance

**Comment by sdruskat** [comment]
@all-contributors please add @sdruskat and @thomaskrause  for code, content, doc, funding-finding, ideas, infra, question, review, test, talk

**Comment by sdruskat** [comment]
@all-contributors please add @thomaskrause for code, content, doc, funding-finding, ideas, infra, question, review, test, talk.

**Comment by sdruskat** [comment]
@all-contributors, please add @VolkerGast for business and projectManagement

**Comment by sdruskat** [comment]
@all-contributors, please add @AnkeLuedeling for business and projectManagement

**Comment by sdruskat** [comment]
Guess this fixes #120 once all 4 PRs are merged?

**Comment by thomaskrause** [comment]
@all-contributors please add @thomaskrause for code, content, doc, funding-finding, ideas, infra, question, review, test, talk.

**Comment by sdruskat** [comment]
Only feature requests should be automatically added via the all contributors bot.

Pull requests should only be credited (e.g., for `code`) when they are merged.
Bug fixes should only be credited if the bug is verified.
Both changes will have to be made manually by calling the bot...
