### ISSUE TITLE
Bundle Java runtimes with Hexatomic

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#20]
To make Hexatomic truly platform-independent, we should bundle a 1.8 JRE with it.

AFAIK, there are two options:

1. Bundle JRE manually per root files
    - Create a feature (I think it was one per OS)
    - Download and put JRE into rootfiles
2. Deploy them to a p2 repo and use `SetJvm`, cf. [SO comment](http://web.archive.org/web/20190813185618/https://stackoverflow.com/questions/49634316/bundle-jre-with-rcp-plugin-based-application-by-tycho-maven/50303681), [blog post](http://web.archive.org/web/20190813185600/https://codeiseasy.wordpress.com/2012/07/31/including-a-jre-in-a-tycho-build/), [GitHub project](https://github.com/buchen/bundled-jre)

**Comment by thomaskrause** [comment]
Eclipse now provides the [just](https://www.eclipse.org/justj/?page=documentation#products) OpenJDK distribution which is also used in their installer. They have a sample product how to integrate it into a Tycho build which we should use: https://www.eclipse.org/justj/?page=documentation#products
