### ISSUE TITLE
TestGraphEditor.testShowSaltExample times out 

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#202]
**Describe the bug**

On a new machine, with a fresh clone of hexatomic, the integration tests fail with the following trace on `mvn clean install`.

```
Running org.corpus_tools.hexatomic.it.tests.TestGraphEditor
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.776 s <<< FAILURE! - in org.corpus_tools.hexatomic.it.tests.TestGraphEditor
testShowSaltExample  Time elapsed: 5.629 s  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Viewport location Point(25.0, 0.0) not reached, was Point(22.0, 0.0) instead
	at org.corpus_tools.hexatomic.it.tests.TestGraphEditor.testShowSaltExample(TestGraphEditor.java:283)
```

**Expected behavior**

Tests pass with `mvn clean install`.

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Hexatomic Version: develop
 - Java Version: AdoptOpenJDK 11

**Comment by sdruskat** [comment]
Test also fails in Eclipse, it seems that zooming in doesn't work.

**Comment by thomaskrause** [comment]
I get the same error from the command line with Maven, but it works when running the tests from Eclipse. I check if the locale has something to do with it.

**Comment by thomaskrause** [comment]
This is in fact related to #192 and the keyboard layout issue. When executing the current code on my machine, the <kbd>Shift</kbd><kbd>+</kbd> gets translated to <kbd>Shift</kbd><kbd>=</kbd>. We might have interpreted the semantics of the keyboard layout wrong and maybe it needs to be set to the actual keyboard which is present on the system and not to a static one. #127 might have been the result of an inconsistency between the display locale and the used keyboard.

**Comment by thomaskrause** [comment]
Actually, using <kbd>Ctrl</kbd>+<kbd>+</kbd> as a shortcut for zooming in seems to be extremely unusable for en_US keyboards since this means they have to press the Shift modifier key as well. My suggestion would be to use the keyboard mapping as it is in develop, but use a shortcut where we are sure the key is present without modifier on as many keyboard layouts as possible.
