### ISSUE TITLE
Automate deployment of documentation and binaries via CI

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#23]
- [x] Add docs and test for auto-deployment to hexatomic.github.io/hexatomic (user + dev/maintainer docs)
- [x] Deploy zips to GitHub release via Travis

**Comment by sdruskat** [comment]
Docs should work, to test during first release.

**Comment by thomaskrause** [comment]
Implemented, will do a test run with a test-tag before submitting this PR

**Comment by thomaskrause** [comment]
Test run was successful
