### ISSUE TITLE
Add About page with basic version metadata

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#241]
**Is your feature request related to a problem? Please describe.**

Hexatomic shold include an `About` page which displays /product) version and citation information for the currently running instance, ideally also included plugins.

**Describe the solution you'd like**

Implement this via the Eclipse platform.

**Describe alternatives you've considered**

n/a

**Additional context**

About pages often have some sort of CD, but as we don't yet have this for Hexatomic, keep it plain.

**Comment by thomaskrause** [comment]
Closed by #251
