### ISSUE TITLE
Document maintenance scope

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#277]
- [x] Document what a maintainer has to do in this project

**Comment by sdruskat** [comment]
@thomaskrause We should discuss thses, and make sure that they're complete. Here's a draft:

## Code review

- Review code (guidelines?)
- Document & triage unreviewed code

## Maintenance work

- Make sure that everything is in place and that everything builds
- Remove code smells, security issues, bugs, etc., that show up during CI

## Releases

- Make releases
- Publicize new releases

## Contributions

- Make sure that citation information is up-to-date
- Make sure that contributors list is up-to-date
- Perform code reviews on contributions
- Decide whether contributions are accepted

## Issues

- Communicate with issue authors: answer questions, suggest fixes (or make them
  yourself if possible or necessary)
- Issue housekeeping: check open issues regularly, and fix + close where possible

## Documentation

- User docs (make sure they are up-to-date with each contribution)
- Dev docs (make sure they are up-to-date with each contribution and document
  the current state of the practice)

## Prepare maintainer changes

- Prepare repositories for takeover
- Document takeover

## Communication & community work

- Publicize releases
- Answer questions outside of the issues, or guide towards issue tracker
- Update external resources

**Comment by thomaskrause** [comment]
> Remove code smells, security issues, bugs, etc., that show up during CI

If there are no PRs, there will probably be no notifications from CI. I think for Maven projects known security issues reporting by GH can be configured to also add a PR in case a dependency should be updated. Also, removing existing code smells sounds like too much to ask for. They shouldn't be introduced in the first case.

Otherwise I think that should cover all, but there are some duplicated elements (like publicize releases)

**Comment by sdruskat** [comment]
Thanks. further disco in #310 :)

**Comment by sdruskat** [comment]
> I think for Maven projects known security issues reporting by GH can be configured to also add a PR in case a dependency should be updated.

Dependabot is already activated, I just doubl-checked.
