### ISSUE TITLE
Document code review process and technology in maintainer documentation

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#32]
The maintainer docs should include an accessible description of how code reviews are done, and what technologies (GitHub, Markdown) are involved. This should really be a 101-style basic introduction that can be shared with users who are requested for reviews by the maintainer.

**Comment by thomaskrause** [comment]
This is now part of the developer documentation: https://hexatomic.github.io/hexatomic/dev/v0.8/maintenance/contributions/index.html#maintaining-pull-requests
