### ISSUE TITLE
Taking over as maintainer

### ISSUE THREAD

**Issue by bbunzeck** [hexatomic/hexatomic#320]
Hello,
I would like to take over as the (temporary) project maintainer. As the last release was just two weeks ago, I hope the old maintainers are still around. @thomaskrause @sdruskat ?
Would you be so kind to grant me administrative rights for the project repository?

**Comment by thomaskrause** [comment]
Hello,
thanks for taking over maintainership! I have made you the owner of the organization, which should also give you ownership over all repositories including this one.
