### ISSUE TITLE
Remove Eclipse/Maven-specific .settings files

### ISSUE THREAD

**Issue by stephandruskat** [hexatomic/hexatomic#332]
**Describe the bug**

Eclipse/Maven-specific `.settings` directories and the containing `*.pref` files should not be check in. In the past, this has led to erors when newly importing the Hexatomic codebase in Eclipse, as pref settings may differ.

**Expected behavior**

A clean checkout of, e.g., `master` should always be importable into Eclipse, and work without throwing errors after setting the target platform.

I'll fix this in a PR.

**Comment by sdruskat** [comment]
Fixed in #343.
