### ISSUE TITLE
Automatic "deployment" of artifacts to release doesn't work

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#348]
**Describe the bug**

As described by @bbunzeck, not all artifacts are automatically added to releases. Instead, manual upload is necessary.

**To reproduce the bug**

Check upon release.

**Expected behavior**

All artifacts for all platforms end up on the release page.

**Additional context**

May be to do with the split-up of builds across OS (MacOS needs to sign on an OS system). May be a race condition.

**Comment by sdruskat** [comment]
@thomaskrause Should we close this for now as we have a separate release workflow for macOS?

**Comment by thomaskrause** [comment]
Yes, since the release workflow now produces also a working macOS artifact, we can close this.
