### ISSUE TITLE
Update `version` in `CITATION.cff` automatically

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#356]
**Describe the bug**

The `version` field in `CITATION.cff` isn't updated automatically.

**To reproduce the bug**
1. Compare the versions in `./pom.xml` and `./CITATION.cff` (both from current `develop` state, same is true for `main`):

https://github.com/hexatomic/hexatomic/blob/a963811f480ec6fdb93a63f2072cf31e5b90af82/pom.xml#L7

https://github.com/hexatomic/hexatomic/blob/a963811f480ec6fdb93a63f2072cf31e5b90af82/CITATION.cff#L11

**Expected behavior**

Both files show the same version.

This could be done by automatically updating CITATION.cff on pushes to the respective branches, at specific checkpoints, i.e., after releases, when the version is updated via the GitFlow Maven plugin. (CFF will not reflect version perfectly in all granularity for all commits, but this is fine.)

**Comment by sdruskat** [comment]
This is an action currently under development that may solve this: https://github.com/atrisovic/update-cff. @sdruskat is in touch with the developers.

**Comment by thomaskrause** [comment]
This has been solved by using the [Maven CFF Plugin](https://github.com/hexatomic/cff-maven-plugin)
