### ISSUE TITLE
Updating CFF file during release doesn't work

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#392]
**Describe the bug**

Underlying bug is https://github.com/hexatomic/cff-maven-plugin/issues/29.

- `mvn -f ./features/org.corpus_tools.hexatomic/pom.xml cff:create` doesn't pull together dependency information.
- Instead, only the information in the CFF template is copied, and `version` and `date-released` added.

**To reproduce the bug**
1. Check out `develop`
2. Run `mvn clean install && mvn -f ./features/org.corpus_tools.hexatomic/pom.xml cff:create` locally
3. Dependencies from `CITATION.cff` are removed rather than updated

This factually blocks further releases running the CFF Maven Plugin in CI.

**Expected behavior**

- CFF is updated:
    - Depedencies are updated
    - `date-released` is updated
    - `version` is updated (during release with release version)

This needs fixing of https://github.com/hexatomic/cff-maven-plugin/issues/29 though.

As interim solution, remove the CFF Maven Plugin run from the release workflow and update CFF manually.

**Additional context**

Related: #391

**Comment by thomaskrause** [comment]
I am not sure that the bug description is correct. The default behavior of the `cff:create` goal is to replace all dependencies and recollect all new ones. This can be important, e.g. when dependencies are removed. Otherwise they would be there forever. If the automatic dependency resolution is not working great (because the information is sparse) you can (and we do) use reference templates. There is a special `skipExistingDependencies` parameter which is true by default (weird) and should allow to explicitiyl set this behavior.

I will try to reproduce the issues you have. But I wonder if the actual bug is, that the dependencies are not generated at all and the dependency list is empty, rather than that the dependencies are not kept in place.

**Comment by thomaskrause** [comment]
Ok, I can reproduce and the list is empty. I am sure that this worked at some point of time :)

**Comment by sdruskat** [comment]
> Ok, I can reproduce and the list is empty. I am sure that this worked at some point of time :)

Yes, it worked at some point :).

Indeed, the bug is that the dependencies list isn't generated. Old dependencies should be removed.

**Comment by thomaskrause** [comment]
The bug was introduced in commit 5beb0f40fcd5c60b56af7ad94b593fd671c2223b and appears to be related to the update to Tycho 2.7.0. There might have been a change if and how the P2 dependencies are mapped as Maven dependencies.

**Comment by sdruskat** [comment]
> The bug was introduced in commit [5beb0f4](https://github.com/hexatomic/hexatomic/commit/5beb0f40fcd5c60b56af7ad94b593fd671c2223b) and appears to be related to the update to Tycho 2.7.0. There might have been a change if and how the P2 dependencies are mapped as Maven dependencies. If this is an intentional change, this is not very "semantic versioning-ly" from Tycho.

I see. Pinning the Tycho dependency doesn't really help in that case, does it, as the plugin will be run depending on the Tycho version the user uses?

**Comment by thomaskrause** [comment]
We could revert to the old Tycho version in the Maven build process (there are ways to specify an upper limit), but this caused problems in the interaction with the Eclipse IDE (I have no idea why, but updating solved it at this time). I will check if there are any  Maven configuration parameters for one of the Tycho plugins I might use to restore the old behavior and will report back. Originally, Tycho exported the P2 dependencies into the Maven dependency graph, which made them available to the CFF plugin.

**Comment by thomaskrause** [comment]
The CFF Maven Plugin uses the `MavenProject#getArtifacts()` call to determine all dependencies. From debugging it, it seems like all bundle projects still have their dependencies resolved. But the feature project hasn't. I will investigate, if we can just change to a different artifact (e.g `org.corpus_tools.hexatomic` or the platform?) to get the dependencies from or if we need a way to aggregate them inside the CFF Plugin. The first variant would be a simple switch of in which artififact the Maven CFF plugin is configured for (and a change in the corresponding documentation). The second variant would need some implementation work in the plugin itself.
