### ISSUE TITLE
Hexatomic connects to GitHub on every startup without asking

### ISSUE THREAD

**Issue by reckart** [hexatomic/hexatomic#412]
**Describe the bug**
Hexatomic connects to GitHub on every startup.

**Expected behavior**
Instead of doing that, a popup should open on the first start asking the user if automatic update checks are acceptable or not. If the user opts out, no such connection should be made.

**Comment by sdruskat** [comment]
Requires #415 to be fixed.

**Comment by thomaskrause** [comment]
To clarify, after #418 is merged, which introduces some refactoring in how the update logic is implemented, we should implement the "do you want to enable auto-updates, this connects to GitHub server" on first startup dialog and store this in the preferences.

The preferences whether to update or not are already implemented, we just have to add the initial dialog.
