### ISSUE TITLE
Preferences not accessible via default means

### ISSUE THREAD

**Issue by reckart** [hexatomic/hexatomic#413]
**Describe the bug**
The preferences are not accessibly via the usual means.

![Screenshot 2022-10-11 at 11 32 43](https://user-images.githubusercontent.com/1410238/195054025-bcdb3158-04fd-48d2-b778-5ffa4c46e162.png)

Instead, the preferences are here:

<img width="140" alt="Screenshot 2022-10-11 at 11 33 08" src="https://user-images.githubusercontent.com/1410238/195054111-6ea38dd9-6700-45f1-956b-b4c9eb8387cf.png">

**Expected behavior**
The preferences should be accessible from the main application menu.

Also, the name of the application should be "Hexatomic" and not " org.corpus_tools.hexatomic".

**Desktop (please complete the following information):**
 - Operating System: MacOS 12.6
 - Hexatomic Version: 1.0.1

**Comment by sdruskat** [comment]
Labeling this as `enhancement` as it isn't a bug as such.
