### ISSUE TITLE
Importing corpus as text (*.txt) also imports non-txt files

### ISSUE THREAD

**Issue by reckart** [hexatomic/hexatomic#421]
**Describe the bug**
Importing corpus as text (*.txt) also imports non-txt files.

**To reproduce the bug**
1. Import a directory containing `*.txt` files as well as other files
2. Select **Import plain text (*.txt)** from the format selection
3. Proceed with import
4. See that the other files are also imported

**Expected behavior**
The dialog clearly says **Import plain text (*.txt)**, so I expect that only `*.txt` files are imported.

**Screenshots**

<img width="499" alt="Screenshot 2022-10-30 at 11 56 09" src="https://user-images.githubusercontent.com/1410238/198874926-16b6fa59-0daa-473f-811a-118caa01d383.png">

**Desktop (please complete the following information):**
 - Operating System: OS X 12.6
 - Hexatomic Version: 1.0.1
 - Java Version: Java 18

**Comment by sdruskat** [comment]
I think this is a side-effect of the Pepper importer for text files working on directories (right, @thomaskrause?). We should investigate whether we can hook into it to filter non-.txt files, or run a post-import action to remove non-.txt files again. The former would be preferable :).

**Comment by thomaskrause** [comment]
Yes, this is a pepper issue and in theory the module registers the known file endings. We should check with the newest Pepper version if this bugs still occurs and fix it there, then using the updated Pepper version.

**Comment by thomaskrause** [comment]
I could reproduce this issue under macOS and Hexatomic 1.1.0. It does work on Linux, so there is more debugging needed for Pepper why it does not correctly filter the files there.
