### ISSUE TITLE
Protection from deleting work

### ISSUE THREAD

**Issue by reckart** [hexatomic/hexatomic#422]
**Is your feature request related to a problem? Please describe.**
Pressing the delete button on a document removes it and undo does not bring it back. That makes it very easy to lose work.

**Describe the solution you'd like**
At least a confirmation dialog if I really want to delete the document.

**Comment by sdruskat** [comment]
Agree, this would be useful!

**Comment by thomaskrause** [comment]
This is actually a bug of the undo function, which should also cover the deletion of documents. It already allows to undo/redo other changes in the corpus graph such as creating documents and sub-corpora.

**Comment by thomaskrause** [comment]
Fixed by #435
