### ISSUE TITLE
Document tagging for part identification

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/hexatomic#48]
Parts (editors/views) that can be used to work on a model element can be gotten via [`tag`](https://wiki.eclipse.org/Eclipse4/RCP/Modeled_UI/Tags)s. We will define specific tags for specific tasks, e.g., `editor-token-based` for editors that work on token-based segmentation, `editor-span-based` for editors which work on spans, etc.

This must be documented in the devl/maintenance docs.

**Comment by thomaskrause** [comment]
This is now solved using categories and also documented (https://hexatomic.github.io/hexatomic/dev/v1.2/development/add-new-editor.html).

The idea of using tags for different kinds of editors is interesting, but not something we will implement in the near future.
